#!groovy
pipeline {
    agent any
    // 环境变量
    environment {
        HARBOR_CREDS = credentials('jenkins-harbor-creds')
        K8S_CONFIG = credentials('jenkins-k8s-config')
        MODULE_1 = "user-dubbo-service"
        MODULE_2 = "user-dubbo-edge-service"
        SCRIPTS_PATH = "scripts/user-service"
        GIT_TAG = sh(returnStdout: true, script: 'git describe --tags --always').trim()
    }

    parameters {
        string(name: 'HARBOR_HOST', defaultValue: '192.168.56.101:8888', description: 'harbor仓库IP')
        string(name: 'DOCKER_IMAGE_1', defaultValue: "jira/user-dubbo-service", description: 'docker镜像名')
        string(name: 'DOCKER_IMAGE_2', defaultValue: "jira/user-dubbo-edge-service", description: 'docker镜像名')
        string(name: 'APP_NAME', defaultValue: 'user-service', description: 'k8s中标签名')
        string(name: 'K8S_NAMESPACE', defaultValue: 'jira', description: 'k8s的namespace名称')
    }

    // 步骤
    stages {
        stage('Maven Build') {
            when { expression { env.GIT_TAG != null } }
            agent {
                docker {
                    image '192.168.56.101:8888/my/my-maven:3-alpine-ali'
                    args '-v /mnt/.m2:/root/.m2'
                }
            }
            steps {
                sh "mvn -U -pl ${MODULE_1}  -am clean package"

                sh "mvn -U -pl ${MODULE_2}  -am clean package"
            }
        }

        stage('Docker Build') {
            when {
                allOf {
                    expression { env.GIT_TAG != null }
                }
            }
            agent any
            steps {
                sh "docker login -u ${HARBOR_CREDS_USR} -p ${HARBOR_CREDS_PSW} ${params.HARBOR_HOST}"

                dir("./${MODULE_1}") {
                    sh "pwd"
                    sh "docker build  -t ${params.HARBOR_HOST}/${params.DOCKER_IMAGE_1}:${GIT_TAG} ."
                    sh "docker push ${params.HARBOR_HOST}/${params.DOCKER_IMAGE_1}:${GIT_TAG}"
                    sh "docker rmi ${params.HARBOR_HOST}/${params.DOCKER_IMAGE_1}:${GIT_TAG}"
                }
                dir("./${MODULE_2}") {
                    sh "pwd"
                    sh "docker build  -t ${params.HARBOR_HOST}/${params.DOCKER_IMAGE_2}:${GIT_TAG} ."
                    sh "docker push ${params.HARBOR_HOST}/${params.DOCKER_IMAGE_2}:${GIT_TAG}"
                    sh "docker rmi ${params.HARBOR_HOST}/${params.DOCKER_IMAGE_2}:${GIT_TAG}"
                }
            }
        }

        stage('Deploy') {
            when {
                allOf {
                    expression { env.GIT_TAG != null }
                }
            }
            agent {
                docker {
                    image 'lwolf/helm-kubectl-docker'
                }
            }
            steps {
                echo "start deploy to k8s"
                sh "mkdir -p ~/.kube"
                sh "echo ${K8S_CONFIG} | base64 -d > ~/.kube/config"
                sh "pwd"

                dir("./${SCRIPTS_PATH}") {
                    sh "pwd"
                    sh "sed -e 's#{IMAGE_URL_1}#${params.HARBOR_HOST}/${params.DOCKER_IMAGE_1}#g;s#{IMAGE_URL_2}#${params.HARBOR_HOST}/${params.DOCKER_IMAGE_2}#g;s#{IMAGE_TAG}#${GIT_TAG}#g;s#{APP_NAME}#${params.APP_NAME}#g;s#{MODULE1}#${MODULE_1}#g;s#{MODULE2}#${MODULE_2}#g' user-service-deployment.tpl > user-service-deployment.yml"
                    sh "kubectl apply -f user-service-deployment.yml "
                }

            }
        }
    }
}