FROM openjdk:8-jre
MAINTAINER xiaoquanxiong@wistronits.com

COPY target/user-dubbo-edge-service-1.0-SNAPSHOT.jar /user-dubbo-edge-service.jar

ENTRYPOINT ["java", "-jar", "/user-dubbo-edge-service.jar"]
